name: Deploy to EC2

on:
  push:
    branches:
      - master  # Change if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd interviewbackend
            git pull origin main
            npm install
            npm run build  # If applicable
            pm2 restart all
